name: Test and Deploy

on:
  push:
    branches:
      - testDev
      - dev
      - main

jobs:
  build:
    runs-on: test

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

  deploy:
    name: Deploy
    runs-on: test

    environment: test

    steps:
      - name: Connect to the server
        uses: appleboy/ssh-action@master
        with:
          host: 10.2.160.9
          username: hamza
          password: student1
          port: 22
          script: |
            cd /home/student/crm/CRM/crm-app
            docker compose down

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Verify Docker and Docker Compose
        run: |
          docker --version &&
          docker-compose --version

      - name: Build Docker images
        run: docker-compose build

      - name: Deploy
        run: |
          docker-compose down --volumes &&
          docker-compose up -d
    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
