name: Test and Deploy

on:
  push:
    branches:
      - testDev
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: test

    env:
      DEV_HOST: 10.2.160.9
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: 5672

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Verify Docker and Docker Compose
        run: |
          docker --version &&
          docker-compose --version

      - name: Navigate to crm-app directory
        run: |
          ls  # Show current directory content
          cd crm-app

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose down

      - name: Build Docker images
        run: docker-compose build

      - name: Deploy
        run: |
          docker-compose up -d

      - name: Check Deployment
        run: echo "Deployment successful"
