name: Test

on:
  push:
    branches:
      - Feat-CI-CD
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment: test
    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Check Docker daemon status
        run: docker info

      - name: Check Docker Compose version
        run: docker compose --version

      - name: Check Docker Compose Syntax
        run: docker compose config --quiet

      - name: Build Docker images
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone git@github.com:Integration-Project-Team-1/xmlxsd.git /app/tmp_validation
          mv /app/tmp_validation/* /src/main/validation
          rm -rf /app/tmp_validation
          sudo apt-get remove -y git
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Deploy
        run: |
          docker compose down --volumes
          docker compose up -d
