name: Test

on:
  push:
    branches:
      - Feat-CI-CD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      SERVER_IP: ${{ secrets.SERVER_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Print Secrets
        run: |
          if [ -n "$DEV_HOST" ]; then echo "DEV_HOST: $DEV_HOST"; fi
          if [ -n "$RABBITMQ_USERNAME" ]; then echo "RABBITMQ_USERNAME: $RABBITMQ_USERNAME"; fi
          if [ -n "$RABBITMQ_PASSWORD" ]; then echo "RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD"; fi
          if [ -n "$SSH_PRIVATE_KEY" ]; then echo "SSH_PRIVATE_KEY is set"; else echo "SSH_PRIVATE_KEY is not set"; fi
          if [ -n "$RABBITMQ_PORT" ]; then echo "RABBITMQ_PORT: $RABBITMQ_PORT"; fi
          if [ -n "$SERVER_IP" ]; then echo "SERVER_IP: $SERVER_IP"; fi

      - name: Deploy
        run: |
          docker compose down --volumes
          docker compose up -d
