name: Test and Deploy

on:
  push:
    branches:
      - testDev
      - dev
      - main

jobs:
  build:
    runs-on: test

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

  deploy:
    name: Deploy
    runs-on: test

    environment:
      name: test
      url: ${{ secrets.DEV_HOST }}
    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}

    steps:
      - name: Get Runner's IP Address
        id: runner_ip
        run: echo "::set-output name=runner_ip::$(hostname -I | cut -d' ' -f1)"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Verify Docker and Docker Compose
        run: |
          docker --version &&
          docker-compose --version

      - name: Navigate to crm-app directory
        run: |
          ls  # Show current directory content
          cd crm-app

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose down

      - name: Build Docker images
        run: docker-compose build

      - name: Set Runner's IP Address in Docker Compose file
        run: |
          sed -i "s/10.2.160.9/${{ steps.runner_ip.outputs.runner_ip }}/" docker-compose.yml

      - name: Deploy
        run: |
          docker-compose up -d

      - name: Check Deployment
        run: echo "Deployment successful"
