on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          if echo "Hello, world!" | grep -q "Hello"; then
            echo "Test passed"
          else
            echo "Test failed"
            exit 1
          fi