name: Test and Deploy

on:
  push:
    branches:
      - testDev
      - dev
      - main

jobs:
  build:
    runs-on: integration-project-dev

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: "Debug: Docker Build"
        run: |
          docker build -t crm-app .
          docker images
        env:
          DEV_HOST: 10.2.160.10
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest
          RABBITMQ_PORT: 5672

  deploy:
    name: Deploy
    runs-on: integration-project-dev

    environment:
      name: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Verify Docker and Docker Compose
        run: |
          docker --version &&
          docker-compose --version

      - name: Navigate to crm-app directory
        run: |
          ls src/main/java/crm  # Show content of crm directory
          cd src/main/java/crm  # Navigate to crm directory

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose -p crm-java-app down

      - name: Build Docker images
        run: docker-compose -p crm-java-app build

      - name: Deploy
        run: |
          docker-compose -p crm-java-app up -d

      - name: Check Deployment
        run: echo "Deployment successful"
