name: Test and Deploy

on:
  push:
    branches:
      - testDev
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          git status
          whoami
          groups
          hostname
          pwd

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment: ubuntu-latest
    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Verify Docker and Docker Compose
        run: |
          docker --version &&
          docker-compose --version

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose -f crm-app/docker-compose.yaml down

      - name: Build Docker images
        run: docker-compose -f crm-app/docker-compose.yaml build

      - name: Deploy
        run: |
          docker-compose -f crm-app/docker-compose.yaml up -d
